### PR TITLE
Event page and Vuex event bugs

### LINKED ISSUE #3: [Events] Build /events/:slug page

### LINKED ISSUE #26: [Bug] Lookahead events disappear after navigating away & back
Possible causes:
- Bad getter structure (using this.$store.state inside Home getter)
- Bad interface with Vuex (using this.$store.state instead of mapState)
- Library might be broken with Vue 3

Possible solutions:
- Move event map to a Vuex getter

See also #27

### LINKED ISSUE #27: [Bug] "Invalid Date" on /events after navigating away & back
See also #26

### PR DESCRIPTION
**Pull request by antonyharfield**
## ✅  DoD

- [x] All work is complete
- [x] Migrations: NA
- [x] Documentation: NA
- [x] Release notes: NA
- [x] Issues linked: resolves #3; resolves #26; resolves #27 

## 📝  Summary

- Initial design for `/events/:slug` page
- Upgrade `@Route` to support `props`
- Dynamic meta
- Inadvertently fix Vuex event loading bugs on events and home (#26, #27)
- Extract `EventUi` model
- Extract date functions
- Restructure project by feature, to group events modules (& add `@assets` alias)

## 💡  More ideas

- Event page should show more data, registration links, etc

## 📸  Screenshots

Screen Shot 2021-04-28 at 12 36 02

### CODE REVIEW

File: hosting/src/models/event.ts [hunk 1]
```diff
@@ -0,0 +1,32 @@
+import dayjs, { Dayjs } from 'dayjs'
```
Comment (charles-allen) [inline hosting/src/models/event.ts]: Why don't we put this file in an `events` package?

File: hosting/src/models/event.ts [hunk 2]
```diff
@@ -0,0 +1,32 @@
...
+  time: string
+  location: string
+  series?: string
+  seriesType?: string
+  badges?: string[]
+  hostId?: string
+  hostName?: string
+  registrationRequired?: boolean
+  registrationUrl?: string
+}
```
Comment (charles-allen) [inline hosting/src/models/event.ts]: This will desync from `common`'s Event quickly. Does this work? Is it preferable?
```
type EventUi = Omit<Event, dateStart | dateEnd> & { 
  dateStart: Dayjs,
  dateEnd: Dayjs
}
```

File: hosting/src/models/event.ts [hunk 3]
```diff
@@ -0,0 +1,32 @@
...
+
+export function eventToEventUi(event: Event): EventUi {
+  const dsDayjs = dayjs.unix(event.dateStart.seconds)
+  const deDayJs = dayjs.unix(event.dateEnd.seconds)
+
+  return {
+    ...event,
+    dateStart: dsDayjs,
+    dateEnd: deDayJs,
+    time: dsDayjs.format('ddd DD MMM, HH:mm') + '-' + deDayJs.format('HH:mm')
```
Comment (charles-allen) [inline hosting/src/models/event.ts]: I think we should remove `time` from this. It's very context sensitive. Can we do it directly in `<template>`?

File: hosting/src/store/index.ts [hunk 4]
```diff
@@ -15,7 +16,13 @@ const store = createStore<PTVuexState>({
     currentUser: null,
     events: []
```
Comment (charles-allen) [inline hosting/src/store/index.ts]: I know you didn't write this, but I was thinking this morning that this should be `futureEvents` not `events`, and we should update the query.

File: hosting/src/store/index.ts [hunk 5]
```diff
@@ -15,7 +16,13 @@ const store = createStore<PTVuexState>({
...
   },
-  getters: {},
+  getters: {
+    events: (state) => state.events.map(eventToEventUi),
```
Comment (charles-allen) [inline hosting/src/store/index.ts]: Re: our discussion on reusing `events` being confusing, do we ever want the raw Firestore version? Perhaps we should rename the state field to `futureEventsRaw` and call the getter `futureEvents`.

File: hosting/src/views/Events/Events.ts [hunk 6]
```diff
@@ -1,40 +1,14 @@
...
-      const deDayJs = dayjs.unix(event.dateEnd.seconds)
-
-      return Object.assign(event, {
-        dateStart: dsDayjs,
-        dateEnd: deDayJs,
-        time: dsDayjs.format('ddd DD MMM, HH:mm') + '-' + deDayJs.format('HH:mm')
-      })
-    })
+  get events(): EventUi[] {
+    return this.$store.getters.events
```
Comment (charles-allen) [inline hosting/src/views/Events/Events.ts]: We probably want to replace this with `mapGetters`

File: hosting/src/views/Event/Event.ts [hunk 7]
```diff
@@ -3,10 +3,15 @@ import { Vue } from 'vue-class-component'
...
+import { EventUi } from '@/models/event'
 import { Route } from '@/router/route-decorator'
 
 @Route({ name: 'Event', path: '/events/:slug' })
 export default class Event extends Vue {
   route = useRoute()
   meta = useMeta(computed(() => ({ title: `Event ${this.route.params.slug as string}` })))
+
+  get event(): EventUi {
+    return this.$store.getters.eventBySlug(this.route.params.slug)
```
Comment (charles-allen) [inline hosting/src/views/Event/Event.ts]: Ah ha! You have reminded me; I have something to show you about decoupling route params!

File: hosting/src/store/index.ts [hunk 8]
```diff
@@ -15,7 +16,13 @@ const store = createStore<PTVuexState>({
...
+    eventBySlug: (state) => (slug: string) => {
+      const event = state.events.find(event => event.slug === slug)
+      return event ? eventToEventUi(event) : undefined
```
Comment (charles-allen) [inline hosting/src/store/index.ts]: How do you feel about a utility function in common: `findMap`
```ts
export const findMap<T, U>(iterable: Iterable<T>?, findFn: (T) => boolean, mapFn: (T) => U): U? {
  const findResult = iterable?.find(findFn)
  return findResult ? mapFn(findResult) : undefined
}
```
...which you could then call:
```ts
getters: {
  events: (state) => map(state.events, eventToEventUi), // lodash map
  eventBySlug: (state) => findMap(state.events, event => event.slug === slug, eventToEventUi)
}
```

**Comment by charles-allen** [comment]
Non-code comments:
- The text needs padding! (it's touching the side)
- Meta title is wrong
- We should add the banner to the meta :)

Screen Shot 2021-04-22 at 10 45 10

File: hosting/src/models/event.ts (hunk 1 above)
Comment (charles-allen) [reply hosting/src/models/event.ts]: Had a go at this... I really like it

Screen Shot 2021-04-22 at 11 00 46

Note: Once the other packages are migrated, `/views` directory would disappear completely, leaving only functional packages: `people`, `home`, etc.

Comment (charles-allen) [reply hosting/src/models/event.ts]: Ran with this a bit, and ended up here:
(again, note that I left `views` because Fa is working on `Spaces` so I don't want to move it)

Screen Shot 2021-04-22 at 11 56 08

File: hosting/src/models/event.ts (hunk 2 above)
Comment (charles-allen) [reply hosting/src/models/event.ts]: DONE

File: hosting/src/models/event.ts (hunk 1 above)
Comment (charles-allen) [reply hosting/src/models/event.ts]: DONE

File: hosting/src/models/event.ts (hunk 3 above)
Comment (charles-allen) [reply hosting/src/models/event.ts]: I tried doing this directly in the template and hated it. It looks terrible. And it appears we do actually reuse it. We should probably extract it as a function. [Filters were removed in Vue 3](https://v3.vuejs.org/guide/migration/filters.html#overview); they suggest registering `$filters` under `globalProperties`.

Comment (charles-allen) [reply hosting/src/models/event.ts]: DONE

File: hosting/src/store/index.ts (hunk 4 above)
Comment (charles-allen) [reply hosting/src/store/index.ts]: If we don't load past events, both `/events` & `/event/:slug` (for past events) need to run their own queries.

I'm starting to think that because we're very events centric, we might actually consider loading ALL events.

Comment (charles-allen) [reply hosting/src/store/index.ts]: DONE - I left it as events (but fixed some types & constants)

File: hosting/src/store/index.ts (hunk 5 above)
Comment (charles-allen) [reply hosting/src/store/index.ts]: DONE - renamed state field to `eventsRaw`

File: hosting/src/views/Events/Events.ts (hunk 6 above)
Comment (charles-allen) [reply hosting/src/views/Events/Events.ts]: I think `mapGetters` doesn't exist in Vuex 4 (for Vue 3). Seems someone has built an extension that restores them: https://github.com/greenpress/vuex-composition-helpers#typescript-mappings.

I don't know if it's worth adding unless it:
a) streamlines our code
-AND-
b) has typescript support

Comment (charles-allen) [reply hosting/src/views/Events/Events.ts]: CLOSED

**Comment by charles-allen** [comment]
> Non-code comments:
> 
> * The text needs padding! (it's touching the side)
> * Meta title is wrong
> * We should add the banner to the meta :)

I've done what I can; fixed the padding & title. The meta for og:image doesn't work. I think crawlers don't enable JS, so we need to enable SSR.

File: hosting/src/views/Event/Event.ts (hunk 7 above)
Comment (charles-allen) [reply hosting/src/views/Event/Event.ts]: I've implemented this in `Event.ts` (at least... the most basic case):
```ts
@Route({ name: 'Event', path: '/events/:slug', props: true })
export default class Event extends Vue.with(class {
  slug!: string
}) {
   ...

  get event(): EventUi | undefined {
    return this.store.getters.eventBySlug(this.slug) // no need to access $route
  }
}
```

The main idea is that Components should not be coupled to `route/$route`; only to `props`. This means multiple routes can use the same Component, even if their params are different. A `vue-router` route definition can provide what is essentially a [mapping function](https://router.vuejs.org/guide/essentials/passing-props.html#function-mode) that converts its params to the Component's props.

If the names & types of params & props are identical, there is also a simpler [boolean switch to pass-thru params](https://router.vuejs.org/guide/essentials/passing-props.html#boolean-mode) (which is all I needed so far).

I will need to improve the type signature for `props` in my decorator to support the function mode.

Comment (charles-allen) [reply hosting/src/views/Event/Event.ts]: DONE

**Review by charles-allen — APPROVED** [review]
lgtm
